export type OauthFormField = {
  enable: boolean;
  clientId: string;
  clientSecret: string;
  clientHost: string;
  serverAuthUrl: string;
  serverTokenUrl: string;
  serverUserIdUrl: string;
  serverLayoutUrl?: string;
  scopes: string;
  accessTokenKeyName: string;
  userIdKeyName: string;
  userEmailTag: string;
  userWechatTag: string;
  autoCreateUser: boolean;
  userPassword?: string;
  skipCheckState: boolean;
  oauth2ButtonText: string;
  loginPermissionQueryGJsonExpression: string;
};
