/**
 *  Generated by actionsky-cli api-mocks, do not modify this file unless necessary.
 *  When modifying the file, please also update the corresponding unit test files.
 */

import {
  IGetSqlVersionListV1Return,
  IGetSqlVersionDetailV1Return,
  IGetWorkflowsThatCanBeAssociatedToVersionV1Return,
  IGetDependenciesBetweenStageInstanceV1Return
} from '@actiontech/shared/lib/api/sqle/service/sql_version/index.d';

export const getSqlVersionListV1MockData = {
  code: 0,
  data: [
    {
      created_at: '2025-03-05T02:01:23.568Z',
      desc: 'now unzip supposing awful solicit enroll mobilize kookily junior dilate hence ferociously smart unless lest alienated modulo onto monster roasted interesting below miscalculate at department bump except dividend skeleton casement precedent soliloquy bind amid overconfidently because unnecessarily aboard however tragic toothbrush regarding vast quicker shyly expostulate uh-huh lumpy with please dish hateful unruly radiant hole weekly yum blah geez modulo gymnast even ick livid sleepily ha inasmuch lest ravioli unfortunately procurement intelligent onto between husband object instead hm tepid quirkily offset starboard luck besides minus linear executor meadow colour under austere shush far innocently gallivant illiterate waist nearly fisherman quaver whoa telescope kindly kowtow now really what limply contradict nab customise lazy times ocelot spellcheck subtract political cumbersome loftily apropos demonstrate busily before selfishly aw amidst busily instead vice intrepid yak scenario where linseed uselessly slowly intently which but ew incidentally of pace lyre reconstitute like so round advocate minus the proper doorpost busily between achieve irk gifted precious yum eke until suddenly fidget pfft even slump out fooey um amused furiously anti yuppify to since',
      lock_time: '2024-12-06T15:24:32.956Z',
      status: 'is_being_released',
      version: 'tentacle',
      version_id: 50,
      deletable: true,
      lockable: true
    },
    {
      created_at: '2025-08-31T03:34:05.561Z',
      desc: 'wordy dally chilly outlying next restaurant toward scuffle for or minor safely yuck gee numb fabricate hence psst that er agitated only reluctantly the beneath atop sometimes scram loudly disposer whoa apparatus oh stoop versus ferociously ew owlishly failing obvious drat interestingly elver even inhibit squeaky fun mmm miscalculate mortally ambitious supposing fill huzzah how instance ah upwardly overvalue failing',
      lock_time: '2024-05-15T00:36:15.825Z',
      status: 'locked',
      version: 'membership',
      version_id: 86,
      deletable: true,
      lockable: true
    },
    {
      created_at: '2024-01-19T07:52:42.274Z',
      desc: 'er haul without thigh think edible zebra on rotating too fairly hmph lest except woot rare coaxingly chap adjudge gerbil in lively home justly elevation pigpen optimistic super commonly mmm outside even democratize psst politely ah decision lest contractor yawningly construe nimble towards collectivization dial boo desk supposing huzzah afore indeed tensely without broken an vet manage um on accidentally',
      lock_time: '2025-04-11T20:52:10.531Z',
      status: 'locked',
      version: 'attraction',
      version_id: 31
    },
    {
      created_at: '2024-05-26T11:46:05.089Z',
      desc: 'gah ha aside ambitious er preregister even mosh midst hypothesize correctly meanwhile on interviewer times far um penalise horde phooey underachieve unnaturally ha in psst even along sadly whimsical which that although colorfully drat wolf merit gift extroverted squeaky provided essence yippee ring yum drat yieldingly furthermore warmhearted hastily greedily flimsy institute esteemed an notwithstanding than caring aware though plagiarise geez dearly blah and synthesise usefully seal pave into underachieve sans father immediate provided quickly loosely yum calmly hmph where whoever exterior whoever pleased burdensome huddle swear excitable uselessly zowie fooey lotion candid multicolored traditionalism ugly till entwine chubby mmm aside slink inexperienced because indeed kaleidoscopic greatly meanwhile forgery chairperson frank rosin wordy gah limply noteworthy below yeast relative yum a whether leading vibraphone pro across disapprove yum once mmm amid perfectly however light fooey adviser considering optimistic interestingly pertain in vice swathe indeed questioningly fake record finally boohoo hm since comb acidly transparency providence helpfully precious opposite if whose once how instead impassioned whoever inventory round when victoriously brr throughout if geez sternly provided inferior birdcage dispose',
      lock_time: '2024-12-03T07:13:41.515Z',
      status: 'locked',
      version: 'institute',
      version_id: 33
    }
  ],
  message: 'ok',
  total_nums: 4
} as IGetSqlVersionListV1Return;

export const getSqlVersionDetailV1MockData = {
  code: 0,
  data: {
    desc: 'inscribe whistle apud till vice knickers circa against wilted supposing colour strictly meh tennis crowded behind whenever phooey weekly nor wobbly woot ew forenenst hope annually ick fooey precious of oil zowie good pocket-watch geez foot upsell key vengeful ring concerning hence attest dredger mystify for reward jot bah beside procrastinate nicely indeed even adventurously properly napkin tempting climb mobilize during regal before considering athwart ligate perfectly righteously hence pro anenst fooey eternity whereas whose ownership gym trash for certainly till instantly rue sedately after indeed wherever why regal while zowie',
    sql_version_id: 80,
    sql_version_stage_detail: [
      {
        stage_id: 79,
        stage_instances: [
          {
            instances_id: '1739531854064652288',
            instances_name: 'mysql-1'
          },
          {
            instances_id: '1739531942258282496',
            instances_name: 'mysql-2'
          }
        ],
        stage_name: 'haircut',
        stage_sequence: 73,
        workflow_details: [
          {
            desc: 'drat quinoa however notwithstanding courteous obediently above gee consequently although plus aha by bludgeon so barring incidentally over heavy ah boohoo nor pricey duh pro knavishly ick delirious geez yippee challenge unto emergent fiercely advocate under blindly motionless extremely as from ack dicker assist suckle travel repentant worthless lest now boss given with blissfully venture behest circa free who ultimately eek muted woot inasmuch rewrite pish gosh while naughty furthermore below yowza blindly oof behind when twin worriedly boo scent boring um experienced till convince fooey ugh barring jealous reprove circa limply given save between stint coarse courageously if importance hepatitis fatally in furthermore ew geez between zowie whereas entire drat lovingly ick out or nor creaking although before duh minus unimpressively overplay summary loudly popularize couch long-term forceful intrepid perky duh marvelous shabby yowza eyeliner hm strategy see cleverly dress with smoggy dishonor under unfortunately ordinary conservative starch diligently well-off overwork through scowl yowza adrenalin tedious filthy hopeful legislature numeracy fooey furlough excepting analyse but while broadly till mmm',
            status: 'wait_for_audit',
            workflow_exec_time: '2025-04-27T01:46:32.187Z',
            workflow_id: 'deed',
            workflow_instances: [
              {
                instance_schema: 'trash',
                instances_id: 'pick',
                instances_name: 'decryption'
              },
              {
                instance_schema: 'simple',
                instances_id: 'jacket',
                instances_name: 'giant'
              },
              {
                instance_schema: 'pupil',
                instances_id: 'forgery',
                instances_name: 'poppy'
              },
              {
                instance_schema: 'finger',
                instances_id: 'schnitzel',
                instances_name: 'brook'
              }
            ],
            workflow_name: 'publicity',
            workflow_release_status: 'released',
            workflow_sequence: 76
          },
          {
            desc: 'pulp enroll than duh lustrous despite for toe with er pantyhose accentuate ugh during er drat cutlet amid whether abnegate delightfully before hope uh-huh scorpion aboard near raw yet co-producer cruelty sinful purse interviewer anenst apud huzzah abscond solemnly generously usually sleet the incidentally toward until anti quizzically flimsy finally behind and futon vol unless humble sorrowful astride afore intensely blah modulo state too paltry kissingly at outsource blossom yum mealy boohoo about concerning tromp import quizzically slowly velocity hm gadzooks snow insidious geez failing um veto chromakey geez discrete linseed rare bah gadzooks happy gleefully eek window chops yippee midst eke second yahoo handsome till despite likewise obvious redound enormously except putrid surprise only beside brr surprisingly experience ferociously even dredger after incidentally requite er sonata instead pfft mad upwardly meh pish solace offensively as finally considering if er yearly in shyly kissingly circa for alongside better display',
            status: 'wait_for_audit',
            workflow_exec_time: '2024-07-11T07:11:15.631Z',
            workflow_id: 'mousse',
            workflow_instances: [
              {
                instance_schema: 'muscat',
                instances_id: 'dead',
                instances_name: 'pension'
              }
            ],
            workflow_name: 'mortise',
            workflow_release_status: 'released',
            workflow_sequence: 87
          }
        ]
      },
      {
        stage_id: 53,
        stage_instances: [
          {
            instance_schema: 'skyline',
            instances_id: 'editor',
            instances_name: 'heartbeat'
          },
          {
            instance_schema: 'going',
            instances_id: 'agreement',
            instances_name: 'scale'
          }
        ],
        stage_name: 'institute',
        stage_sequence: 80,
        workflow_details: [
          {
            desc: 'atop sans excitedly own larva meh swordfish sunbeam rewrite as whoa lox mismatch beret recount austere ravioli loyalty shaft apropos nervously accompanist guilt whenever readjust ah abaft following indeed pertinent since molasses cinema reward huzzah blah when pike sprinkles ditch unless microchip though woot moral neglected zealous politely encouragement who forgo toward furthermore hastily so sniff whose enchanting sashay for instead the via hornet sprinkles blah first grok colorfully clone sparkling acquaintance phooey telescope whereas ack where acidly alongside given punctually whoa lasting practical lasting indeed since since cash moor on help gah team yowza burgeon cafe key down of though brochure efface wherever runny grave beneficial meanwhile brr finally fine hydrocarbon custom doubtfully t-shirt as which emphasize consistency mmm cleaner exonerate yippee fully until of creature ah twine gaseous gee wherever tinderbox mmm inhibit heartfelt disarm toady admired blacken consequently similar aw provider while handful hydrant intent gigantic unnaturally curse while upside-down naturally pish whoa apricot bicycle bah er till an whoa substitution misjudge modulo mask gigantic bus scholarship peninsula yet unnecessarily optimistically unsightly fidget gosh independence',
            status: 'wait_for_audit',
            workflow_exec_time: '2024-07-24T01:55:54.941Z',
            workflow_id: 'forager',
            workflow_instances: [
              {
                instance_schema: 'deer',
                instances_id: 'planula',
                instances_name: 'heroine'
              },
              {
                instance_schema: 'pension',
                instances_id: 'swine',
                instances_name: 'igloo'
              }
            ],
            workflow_name: 'blight',
            workflow_release_status: 'released',
            workflow_sequence: 71
          },
          {
            desc: 'outside geez inasmuch igloo elderly who since hm drat neaten overconfidently um yowza pecan reword sharply charming sandbar whoever serialize hmph place ah inventory but swordfish yawningly hundred intensely inscribe gleefully icebreaker deploy with naughty trivial violently bewail deplore sand brightly comfortable tabulate schedule charlatan warmhearted speedily er twin aw marten of aboard furthermore furthermore whoa frequent ill-fated archive furthermore spark break bossy switch comestible finally past married supposing quizzically different enrich tensely severe finer deeply frizz including willfully anti typewriter helpfully following adjourn provider whenever huzzah aha fictionalize afraid monstrous cheerfully uh-huh potable unusual out sundae hungry indeed fuel astride ripe airbrush range duh pace likewise male scratchy steel notwithstanding stark browse gracious amid splurge geez reasoning bah huddle although massage hundred aw although coil pace slowly phony knight concrete gentle openly overconfidently because cooperative wretched thoughtfully encouragement beside excluding brr fondly mid memorise culture while beyond what generally faithfully silver quizzically among finally when now past schedule emphasize royal sorrowful absent times',
            status: 'wait_for_audit',
            workflow_exec_time: '2025-04-27T21:53:26.600Z',
            workflow_id: 'barracks',
            workflow_instances: [
              {
                instance_schema: 'abacus',
                instances_id: 'design',
                instances_name: 'climb'
              }
            ],
            workflow_name: 'license',
            workflow_release_status: 'released',
            workflow_sequence: 75
          }
        ]
      },
      {
        stage_id: 34,
        stage_instances: [
          {
            instance_schema: 'help',
            instances_id: 'hunt',
            instances_name: 'section'
          },
          {
            instance_schema: 'cutover',
            instances_id: 'ecliptic',
            instances_name: 'remark'
          }
        ],
        stage_name: 'horde',
        stage_sequence: 86,
        workflow_details: [
          {
            desc: 'across fisherman provided ferociously anguished times manipulate',
            status: 'wait_for_audit',
            workflow_exec_time: '2024-11-29T20:01:35.931Z',
            workflow_id: 'dead',
            workflow_instances: [
              {
                instance_schema: 'labourer',
                instances_id: 'moment',
                instances_name: 'operating'
              },
              {
                instance_schema: 'plain',
                instances_id: 'pantyhose',
                instances_name: 'spear'
              }
            ],
            workflow_name: 'drug',
            workflow_release_status: 'released',
            workflow_sequence: 85
          },
          {
            desc: 'reproachfully when psst eek instantly vain beautifully supposing',
            status: 'wait_for_audit',
            workflow_exec_time: '2025-04-10T17:28:40.318Z',
            workflow_id: 'hygienic',
            workflow_instances: [
              {
                instance_schema: 'swanling',
                instances_id: 'integer',
                instances_name: 'coast'
              },
              {
                instance_schema: 'onset',
                instances_id: 'dredger',
                instances_name: 'airbus'
              }
            ],
            workflow_name: 'grandpa',
            workflow_release_status: 'released',
            workflow_sequence: 68
          }
        ]
      }
    ],
    status: 'locked',
    version: 'coast'
  },
  message: 'ok'
} as IGetSqlVersionDetailV1Return;

export const GetWorkflowsThatCanBeAssociatedToVersionV1MockData = {
  code: 0,
  data: [
    {
      desc: 'galoshes ack pretend cardboard drum deceivingly beside guilt sometimes polyester consequently moist boohoo perky construe submissive valiantly honesty indeed preheat greedily after worth scotch animated toward eek zowie numeric sustenance never ah than through quirkily cop-out gadzooks deliberately afore reasonable boo jacket anguished however rough round except orchid brand haversack mortally airbrush or fashion please er among bleakly underneath courageous zowie overload honestly jaywalk harangue clearly garage pulse unlike circumnavigate dearly unethically fess frivolous gloom pause yahoo pace bah hippodrome',
      status: 'wait_for_audit',
      workflow_id: 'approach',
      workflow_name: 'exhaust'
    },
    {
      desc: 'granular whenever pocket-watch bossy chubby gah but however orange cork absentmindedly hence flat depart digit mmm paltry every sedately blue truly reconsideration skean till form in though allegation reconsideration in so likewise splurge refute rawhide prime monthly brief instantly an greatly institute that however aha gummy excess wetly properly beautifully phew apropos pfft gummy decongestant verbally though timely after likely during impostor inasmuch scotch orchestrate beloved besides early but too who consequently woot outbid geez yieldingly within victorious specific not weary concrete rebel truthfully custody since geez sinful sprinkles switchboard confused past gah now frankly but even modulo platypus before ugh for tensely oof of procurement whether depot ah institutionalize even midst till papa fooey hence viciously opposite extremely around gladly rapidly psst blah putrefy reiterate indelible suitcase the any anti hello roughly through machine desecrate',
      status: 'wait_for_audit',
      workflow_id: 'overload',
      workflow_name: 'sailor'
    },
    {
      desc: 'embody cleverly justly blah around yahoo distinction bare harangue however upset yuck upon reassuringly executor inasmuch truly meh monthly owlishly underneath aha innocently outlandish juvenile in whoever',
      status: 'wait_for_audit',
      workflow_id: 'straw',
      workflow_name: 'resource'
    }
  ],
  message: 'ok'
} as IGetWorkflowsThatCanBeAssociatedToVersionV1Return;

export const getDependenciesBetweenStageInstanceV1MockData = {
  code: 0,
  data: [
    {
      next_stage_instance_id: 'allocation',
      next_stage_instance_name: 'edge',
      stage_instance_id: 'stall',
      stage_instance_name: 'stir-fry'
    }
  ],
  message: 'ok'
} as IGetDependenciesBetweenStageInstanceV1Return;
