// Generated by actionsky-cli api-mocks, do not modify this file.

import database_comparison from '@actiontech/shared/lib/api/sqle/service/database_comparison';
import { createSpySuccessResponse } from '@actiontech/shared/lib/testUtil/mockApi';
import {
  executeDatabaseComparisonMockData,
  genDatabaseDiffModifySQLsMockData,
  getComparisonStatementMockData
} from './data';

class DatabaseComparisonMockService {
  public mockAllApi(): void {
    this.mockGetComparisonStatementV1();
    this.mockExecuteDatabaseComparisonV1();
    this.mockGenDatabaseDiffModifySQLsV1();
  }

  public mockGetComparisonStatementV1() {
    const spy = jest.spyOn(database_comparison, 'getComparisonStatementV1');
    spy.mockImplementation(() =>
      createSpySuccessResponse({ data: getComparisonStatementMockData })
    );
    return spy;
  }

  public mockExecuteDatabaseComparisonV1() {
    const spy = jest.spyOn(database_comparison, 'executeDatabaseComparisonV1');
    spy.mockImplementation(() =>
      createSpySuccessResponse({ data: executeDatabaseComparisonMockData })
    );
    return spy;
  }

  public mockGenDatabaseDiffModifySQLsV1() {
    const spy = jest.spyOn(database_comparison, 'genDatabaseDiffModifySQLsV1');
    spy.mockImplementation(() =>
      createSpySuccessResponse({ data: genDatabaseDiffModifySQLsMockData })
    );
    return spy;
  }
}

export default new DatabaseComparisonMockService();
