name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main, 'main-ee', release*, 'temporary/**']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip checker]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/catch-install-pnpm

      - name: Code lint checker
        run: pnpm checker

  test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip checker]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/catch-install-pnpm

      - name: Run package test suites
        run: pnpm test:ci:turbo

      - name: Upload base coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts-base
          path: packages/base/coverage/

      - name: Upload dms-kit coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts-dms-kit
          path: packages/dms-kit/coverage/

      - name: Upload shared coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts-shared
          path: packages/shared/coverage/

      - name: Upload sqle coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts-sqle
          path: packages/sqle/coverage/

  report:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip checker]') }}
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Coverage 1
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifacts-base
          path: coverage/base

      - name: Get Coverage 2
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifacts-dms-kit
          path: coverage/dms-kit

      - name: Get Coverage 3
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifacts-shared
          path: coverage/shared

      - name: Get Coverage 4
        uses: actions/download-artifact@v4
        with:
          name: coverage-artifacts-sqle
          path: coverage/sqle

      - name: Coverage report (base)
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage/base/report.json

      - name: Coverage report (dms-kit)
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage/dms-kit/report.json

      - name: Coverage report (shared)
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage/shared/report.json

      - name: Coverage report (sqle)
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage/sqle/report.json

      - name: Delete coverage artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            coverage-artifacts-base
            coverage-artifacts-dms-kit
            coverage-artifacts-shared
            coverage-artifacts-sqle
